from __future__ import annotations

import json
import shlex
import sys
from pathlib import Path

from .git import find_repo_root
from .setup import SetupResult


TEAM_DOC_START = "<!-- EDGEBASE:TEAM:START -->"
TEAM_DOC_END = "<!-- EDGEBASE:TEAM:END -->"


def team_init(root: str | Path, mode: str) -> list[SetupResult]:
    if mode not in {"optional", "required"}:
        raise ValueError("team mode must be optional or required")
    repo_root = find_repo_root(root)
    results = [write_team_docs(repo_root, mode)]
    if mode == "required":
        hook_path = write_required_hook(repo_root)
        results.append(SetupResult(hook_path, "updated", "Edgebase required-mode Claude hook script"))
        settings_path = install_required_hook(repo_root, hook_path)
        results.append(SetupResult(settings_path, "updated", "Edgebase required-mode Claude PreToolUse hook"))
    return results


def team_disable(root: str | Path) -> list[SetupResult]:
    repo_root = find_repo_root(root)
    return [
        remove_team_docs(repo_root),
        SetupResult(uninstall_required_hook(repo_root), "updated", "removed Edgebase required-mode Claude hook"),
    ]


def write_team_docs(repo_root: Path, mode: str) -> SetupResult:
    path = repo_root / "AGENTS.md"
    block = team_doc_block(mode)
    if not path.exists():
        path.write_text("# Agent Instructions\n\n" + block, encoding="utf-8")
        return SetupResult(path, "created", f"Edgebase team mode ({mode})")
    existing = path.read_text(encoding="utf-8")
    if TEAM_DOC_START in existing and TEAM_DOC_END in existing:
        before, rest = existing.split(TEAM_DOC_START, 1)
        _, after = rest.split(TEAM_DOC_END, 1)
        updated = before.rstrip() + "\n\n" + block + after
    else:
        updated = existing.rstrip() + "\n\n" + block
    path.write_text(updated.rstrip() + "\n", encoding="utf-8")
    return SetupResult(path, "updated", f"Edgebase team mode ({mode})")


def team_doc_block(mode: str) -> str:
    if mode == "required":
        body = (
            "## Edgebase Required\n\n"
            "This repo requires Edgebase for AI-assisted implementation work. Before broad code exploration or edits, "
            "verify `edgebase doctor --scope both` and use the active Goal Capsule / Work Contract flow. If Edgebase "
            "is missing, install it with `edgebase install-prompt --agent all` and restart the agent.\n"
        )
    else:
        body = (
            "## Edgebase Recommended\n\n"
            "This repo recommends Edgebase for AI-assisted work. Install once, then use Goal Capsules, active Work "
            "Contracts, status, checkpoints, and Patch Passports instead of manually rebuilding context each session.\n"
        )
    return f"{TEAM_DOC_START}\n{body}{TEAM_DOC_END}\n"


def remove_team_docs(repo_root: Path) -> SetupResult:
    path = repo_root / "AGENTS.md"
    if not path.exists():
        return SetupResult(path, "skipped", "AGENTS.md not found")
    existing = path.read_text(encoding="utf-8")
    if TEAM_DOC_START not in existing or TEAM_DOC_END not in existing:
        return SetupResult(path, "skipped", "Edgebase team marker not found")
    before, rest = existing.split(TEAM_DOC_START, 1)
    _, after = rest.split(TEAM_DOC_END, 1)
    path.write_text((before.rstrip() + after).strip() + "\n", encoding="utf-8")
    return SetupResult(path, "updated", "removed Edgebase team marker")


def write_required_hook(repo_root: Path) -> Path:
    path = repo_root / ".claude" / "hooks" / "edgebase-required.sh"
    path.parent.mkdir(parents=True, exist_ok=True)
    command = shlex.join(
        [
            sys.executable,
            "-m",
            "edgebase",
            "doctor",
            "--root",
            str(repo_root),
            "--scope",
            "project",
            "--agents",
            "claude",
            "--json",
        ]
    )
    path.write_text(
        "#!/bin/sh\n"
        "# Edgebase required-mode hook. Generated by `edgebase team init required`.\n"
        f"if ! {command} >/dev/null 2>&1; then\n"
        "  echo '{\"permissionDecision\":\"deny\",\"permissionDecisionReason\":\"Edgebase is required for AI-assisted edits in this repo. Run edgebase install-prompt --agent all.\"}'\n"
        "  exit 0\n"
        "fi\n"
        "echo '{}'\n",
        encoding="utf-8",
    )
    path.chmod(0o755)
    return path


def install_required_hook(repo_root: Path, hook_path: Path) -> Path:
    settings_path = repo_root / ".claude" / "settings.json"
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    settings: dict[str, object] = {}
    if settings_path.exists():
        loaded = json.loads(settings_path.read_text(encoding="utf-8"))
        if isinstance(loaded, dict):
            settings = loaded
    hooks = settings.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        raise RuntimeError(f"Expected hooks object in {settings_path}")
    entries = hooks.setdefault("PreToolUse", [])
    if not isinstance(entries, list):
        raise RuntimeError(f"Expected PreToolUse list in {settings_path}")
    entry = {
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [{"type": "command", "command": shlex.quote(str(hook_path)), "timeout": 10}],
    }
    if entry not in entries:
        entries.append(entry)
    settings_path.write_text(json.dumps(settings, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return settings_path


def uninstall_required_hook(repo_root: Path) -> Path:
    settings_path = repo_root / ".claude" / "settings.json"
    if settings_path.exists():
        loaded = json.loads(settings_path.read_text(encoding="utf-8"))
        if isinstance(loaded, dict):
            hooks = loaded.get("hooks")
            if isinstance(hooks, dict):
                entries = hooks.get("PreToolUse")
                if isinstance(entries, list):
                    hooks["PreToolUse"] = [
                        entry for entry in entries if "edgebase-required.sh" not in json.dumps(entry)
                    ]
                    if hooks["PreToolUse"] == []:
                        del hooks["PreToolUse"]
                if hooks == {}:
                    loaded.pop("hooks", None)
            settings_path.write_text(json.dumps(loaded, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    hook_path = repo_root / ".claude" / "hooks" / "edgebase-required.sh"
    if hook_path.exists():
        hook_path.unlink()
    return settings_path
